---
title: "Homework 1"
author: "Han Nguyen - TXN200004"
date: "09/02/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

## a)

```{r, problem_1a}
a <- round(8 + 9 - 7 / 3^0.3, 2)
```

Answer: $8 + 9 - \frac{7}{3^{0.3}}$ = ```r a```

## b)

```{r, problem_1b}
b <- round(log(sqrt((15 + 6) / (14 + 2)), base = 2), 2)
```

Answer: $\log_2 \left( \sqrt{\frac{15 + 6}{14 + 2}} \right)$ = ```r b```


## c)

```{r, problem_1c}
c <- round(((11 + sin(pi/4)) / (factorial(3) + abs(-10)))^2, 2)
```

Answer: $\left( \frac{11 + \sin\left(\frac{\pi}{4}\right)}{3! + |-10|} \right)^2$ = ```r c```

## d)

```{r, problem_1d}
d <- round(6 + 5 - 4/3^2, 2)
```

Answer: $6 + 5 - \frac{4}{3^2}$ = ```r d```

## e)

```{r, problem_1e}
e <- round(exp( sqrt( (14 + 13) / (12 + 11) ) ), 2)
```

Answer: $e^{\sqrt{\frac{14 + 13}{12 + 11}}}$ = ```r e```

## f)

```{r, problem_1f}
f <- round(((11 + factorial(12)) / (factorial(13) + 14))^2, 2)
```

Answer: $\left( \frac{11 + 12!}{13! + 14} \right)^2$ = ```r f```

# Problem 2

```{r, problem2}
# If I wrote code that would be used in all following letters, it would go here
```

## a)

```{r, problem_2a}
# This is where my code for this question goes
```

## b)

```{r, problem_2b}
# This is where my code for this question goes
```

## c)

```{r, problem_2c}
# This is where my code for this question goes
```

## d)

```{r, problem_2d}
# This is where my code for this question goes
```

# Problem 3

```{r, problem3}
# If I wrote code that would be used in all following letters, it would go here
```

## a)

```{r, problem_3a}
# This is where my code for this question goes
```

## b)

```{r, problem_3b}
# This is where my code for this question goes
```

## c)

```{r, problem_3c}
# This is where my code for this question goes
```

## d)

```{r, problem_3d}
# This is where my code for this question goes
```

# Problem 4
```{r, problem4}
# If I wrote code that would be used in all following letters, it would go here
```

## a)

```{r, problem_4a}
# This is where my code for this question goes
```

## b)

```{r, problem_4b}
# This is where my code for this question goes
```

## c)

```{r, problem_4c}
# This is where my code for this question goes
```

# Problem 5

```{r, problem_5}
# This is where my code for this question goes
```

# Problem 6

```{r, problem_6}
# This is where my code for this question goes
```

