---
title: "Homework 2"
author: "Han Nguyen - TXN200004"
date: "09/16/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

## a)

```{r, problem_1a}
mat <- matrix(c(34, 23, 53, 6, 78, 93, 12, 41, 99), nrow = 3)
df <- as.data.frame(mat)
names(df) <- c("score_given_to_car_on_driving_test",
               "score_given_to_van_on_driving_test",
               "score_given_to_truck_on_driving_test")
```

## b)

```{r, problem_1b}
library(ggplot2)
head(mpg)
second_version_of_mpg <- mpg[mpg$cyl == 6, ]
second_version_of_mpg$class <- as.character(second_version_of_mpg$class)
```

# Problem 2

```{r, problem2}
# Read the csv
senate <- read.csv("1976-2020-senate.csv")
head(senate)
```

## a)

```{r, problem_2a}
# Convert variables to factor
senate$year <- as.factor(senate$year)
senate$state <- as.factor(senate$state)
senate$party_simplified <- as.factor(senate$party_simplified)
```

## b)

```{r, problem_2b}
texas_senates <- subset(senate, 
                        state == "TEXAS", 
                        select = c("year", 
                                   "state", 
                                   "candidatevotes", 
                                   "totalvotes", 
                                   "party_simplified"))
head(texas_senates)
```

## c)

```{r, problem_2c}
# average votes by party
parties <- unique(texas_senates$party_simplified)

avg_votes <- numeric(length(parties))
median_votes <- numeric(length(parties))

# Name for indexing
names(avg_votes) <- parties
names(median_votes) <- parties

# Iterate through each party and calculate avg, median
for (party in parties) {
  avg_votes[party] <- round(mean(
    texas_senates$candidatevotes[texas_senates$party_simplified == party], 
    na.rm = TRUE
  ))
  median_votes[party] <- round(median(
    texas_senates$candidatevotes[texas_senates$party_simplified == party], 
    na.rm = TRUE
  ))
}

for (p in names(avg_votes)) {
  cat(p,"-", "Average votes:", avg_votes[p], "\n")
}

for (p in names(median_votes)) {
  cat(p,"-", "Median votes:", median_votes[p], "\n")
}

```
## d)

```{r, problem_2d}
# Determine years in which DEMOCRAT candidate from TEXAS won
year_won <- texas_senates$year[
  texas_senates$party_simplified == "DEMOCRAT" & 
  texas_senates$candidatevotes == ave(texas_senates$candidatevotes, 
                                      texas_senates$year,
                                      FUN = max)
]
year_won <- as.character(year_won)
cat("Years that Democrat won in Texas: ", year_won)
```

# Problem 3

```{r, problem3}
tae <- read.table("tae.data", sep = ",", header = FALSE)
names(tae) <- c("english_speaker",   # 1 = English speaker, 2 = non-English
                "instructor",        # categorical (25 categories)
                "course",            # categorical (26 categories)
                "regular",          # 1 = Summer, 2 = Regular
                "class_size",        # numeric
                "score")   # 1 = Low, 2 = Medium, 3 = High
# Add TA ID based on row number
tae$TA_ID <- 1:nrow(tae)

head(tae)
```

## a)

```{r, problem_3a}
# Turn first variable into logical variable
tae[, 1] <- tae[, 1] == 1
head(tae)
```

## b)

```{r, problem_3b}
# Turn 4th variable into logical variable
tae[,4] <- tae[,4] == 2
head(tae)
```

## c)

```{r, problem_3c}
# Turn the last variable (class attribute or evaluation score) into an ordered factor variable with levels labeled as ‘low’, ‘medium’ and ‘high’
tae$score <- factor(tae$score,
                    levels = c(1,2,3),
                    labels = c("low", "medium", "high"),
                    ordered = TRUE)
head(tae)
```

## d)

```{r, problem_3d}
# Average
avg_regular <- round(mean(tae$class_size[tae$regular == TRUE], na.rm = TRUE), 2)
avg_summer   <- round(mean(tae$class_size[tae$regular == FALSE], na.rm = TRUE), 2)

# Median
median_regular <- round(median(tae$class_size[tae$regular == TRUE], na.rm = TRUE), 2)
median_summer   <- round(median(tae$class_size[tae$regular == FALSE], na.rm = TRUE), 2)

# Print results with labels
cat("Regular semester - Average:", avg_regular, "Median:", median_regular, "\n")
cat("Summer semester  - Average:", avg_summer,  "Median:", median_summer, "\n")
```

## e)

```{r, problem_3e}
# English speakers
native_regular <- sum(tae$english_speaker & tae$regular)
native_summer  <- sum(tae$english_speaker & !tae$regular)

# Not English speakers
non_native_regular <- sum(!tae$english_speaker & tae$regular)
non_native_summer  <- sum(!tae$english_speaker & !tae$regular)

cat("Native English TAs - Regular:", native_regular, "Summer:", native_summer, "\n")
cat("Non-native English TAs - Regular:", non_native_regular, "Summer:", non_native_summer, "\n")

```

## f)

```{r, problem_3f}
total_native <- sum(tae$english_speaker)
high_native <- sum(tae$english_speaker & tae$score == "high")
prop_native <- round(high_native / total_native, 2)

# Non-native English TAs
total_non_native <- sum(!tae$english_speaker)
high_non_native <- sum(!tae$english_speaker & tae$score == "high")
prop_non_native <- round(high_non_native / total_non_native, 2)

cat("Native English TAs:", total_native, ". High score proportion:", prop_native, "\n")
cat("Non-native English TAs:", total_non_native, ". High score proportion:", prop_non_native, "\n")
```


